routes/web.php
<?php
/* Route::get('/', function () {
    return view('welcome');
}); */

//Auth::routes();

Route::get('{slug}', function() {
    return view('home');
})->where('slug', '(?!api|admin)([A-z\d-\/_.]+)?');

Route::group(['prefix' => 'admin'], function () {
	Route::get('/', 'Auth\LoginController@showLoginForm');
	Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'Auth\LoginController@login')->name('login');
	Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('/dashboard', 'Pages\MainController@index')->name('dashboard');
	Route::get('/user/getdata', 'Pages\UserController@getData')->name('user.data');
	Route::resource('user','Pages\UserController');
	Route::get('/client/getdata', 'Pages\ClientController@getData')->name('client.data');
	Route::get('/client/{client_id}/users', 'Pages\ClientController@getUsers');
	Route::resource('client','Pages\ClientController');
	Route::get('/staff/getdata', 'Pages\StaffController@getData')->name('staff.data');
	Route::resource('staff','Pages\StaffController');
	Route::get('/document/getdata', 'Pages\DocumentController@getData')->name('document.data');
	Route::resource('document','Pages\DocumentController');
	Route::get('/chat', 'Pages\ChatController@index')->name('chat.index');
	Route::post('/chat/{document}', 'Pages\ChatController@store')->name('chat.store');
	Route::get('/chat/{document}', 'Pages\ChatController@getData')->name('chat.data');
	Route::delete('/chat/{document}', 'Pages\ChatController@destroy')->name('chat.destroy');
	Route::get('/message/getdata', 'Pages\ChatController@getMessageData')->name('message.data');
	Route::get("/chat/count/data",'Pages\ChatController@chatCount')->name('chat.count');
	Route::post('/document/{document}/status', 'Pages\DocumentController@changeStatus')->name('document.status');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'username', 'password', 'status', 'parent_user', 'parent_client', 'business_type', 'name_ppd', 'pan_no', 'gst_no', 'mobile', 'address'
    ];

    protected $hidden = [
        'password', 'remember_token', 'updated_at', 'parent_user', 'parent_client', 'created_at'
    ];
	
	public function staffAccess() 
	{
        return $this->hasMany('App\StaffAccess');
    }
	
	public function roles()
    {
        return $this->belongsToMany(Role::class, 'role_users');
    }

    public function hasAccess(array $permissions) : bool
    {
        foreach ($this->roles as $role) {
            if($role->hasAccess($permissions)) {
                return true;
            }
        }
        return false;
    }

    public function inRole(string $roleSlug)
    {
        return $this->roles()->where('slug', $roleSlug)->count() == 1;
    }
	
	public function parentClient() { 
		return $this->belongsTo( 'App\User', 'parent_user', 'id'); 
	}
	
}

app/Http/Controllers/Pages/UserController.php
<?php 
namespace App\Http\Controllers\Pages;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\User;
use Config;
use DataTables;
use Validator;
use Carbon\Carbon;
use Gate;

class UserController extends Controller {
	
	public function __construct() {
        $this->middleware('auth');
		$this->middleware('admin');
    }
	
    public function index()
	{
        return view('pages.user.index');
    }
	
	public function getData()
	{
		$user = Auth::user();
		if($user->inRole('super')){
			$query = User::whereHas('roles', function($q){
				$q->where('slug', 'admin');
			});
		} else if($user->inRole('admin')) {
			$user_id = $user->id;
			$query = User::with(array(
				'parentClient' => function($query){
					$query->select('id', 'name');
				}))->where('parent_client', $user_id);
		}

		return DataTables::eloquent($query)
		->addIndexColumn()
		->addColumn('action', function($user){
			$buttons = '<a href="'.route('user.edit', $user->id).'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
			return $buttons;
		})
		->editColumn('parent_client.name', function($user){
			if($user->parent_client){
				return $user->parentClient->name;
			}
			return "-";
		})
		->editColumn('created_at', function($user){
			return $user->created_at ? with(new Carbon($user->created_at))->format('d/m/Y') : '';
		})
		->filterColumn('created_at', function ($query, $keyword) {
             $query->whereRaw("DATE_FORMAT(created_at,'%d/%m/%Y') like ?", ["%$keyword%"]);
        })
        ->rawColumns(['checkbox', 'action'])
		->toJson();
    }
	
	public function create()
    {
		$data['page_title'] = 'Add User';
		$data['page_description'] = 'Information about user';
		$data['action'] = 'insert';
		$data['url'] = route('user.store');
		$user = Auth::user();
		if($user->inRole('admin')) {
			$data['clients'] = User::whereHas('roles', function($q){
				$q->where('slug', 'client');
			})->where('parent_user',$user->id)->pluck('name', 'id');
		}
		
        return view('pages.user.form', compact('data'));
    }
	
	public function store(Request $request)
    {
		$validator = Validator::make($request->all(), [
            'name' => 'required',
            'user_type' => 'sometimes|required',
            'client_id' => 'required_if:user_type,==,user',
            'username' => 'required|unique:users|max:20',
            'email' => 'nullable|email|unique:users',
            'password' => 'required|min:6',
        ]);
		
		if ($validator->fails()) {
            return response()->json(['errors' => $validator->messages()]);
        }
		
		$login_user = Auth::user();
		$parent_client = 0;
		if($login_user->inRole('super')){
			$parent_user = $login_user->id;
		} else if($login_user->inRole('admin')){
			if($request->input('user_type') == 'client'){
				$parent_user = $login_user->id;
			} else {
				$parent_user = $request->input('client_id');
				$parent_client = $login_user->id;
			}
		}
		
		$user = User::create([
			'name' => $request->input('name'),
			'username' => $request->input('username'),
			'email' => $request->input('email'),
			'password' => bcrypt($request->input('password')),
			'status' => $request->input('status'),
			'parent_user' => $parent_user,
			'parent_client' => $parent_client,
		]);
		
		if($login_user->inRole('super')){
			$user->roles()->attach(2);
		} else if($login_user->inRole('admin')){
			if($request->input('user_type') == 'client'){
				$user->roles()->attach(4);
			} else {
				$user->roles()->attach(3);
			}
		}
		$request->session()->flash('success','User created successfully');
		return response()->json(['success' => true, 'redirect' => route('user.index')]);
	}
	
	public function edit(User $user)
	{
		if (Gate::denies('user-access', $user)) {
			abort(404);
		}
		
		$data['page_title'] = 'Edit User';
		$data['page_description'] = 'Information about user';
		$data['action'] = 'edit';
		
		$data['url'] = route('user.update', $user->id);
		
		$login_user = Auth::user();
		if($login_user->inRole('admin')) {
			$data['clients'] = User::where('parent_user', Auth::user()->id)->pluck('name', 'id');
			$user->user_type = $user->roles[0]->slug;
			if($user->user_type == 'user'){
				$user->client_id = $user->parent_user;
			}
		}
		
        return view('pages.user.form', compact('user', 'data'));
    }
	
	public function update(Request $request, User $user) 
	{
		$validator = Validator::make($request->all(), [
            'name' => 'required',
			'user_type' => 'sometimes|required',
            'client_id' => 'required_if:user_type,==,user',
			'username' => 'required|max:20|unique:users,username,'.$user->id,
            'email' => 'nullable|unique:users,email,'.$user->id,
            'password' => 'min:6|nullable',
        ]);
		
		if ($validator->fails()) {
            return response()->json(['errors' => $validator->messages()]);
        }
		
		if ($request->filled('password')) {
			$data = $request->all();
			$data['password'] = bcrypt($request->input('password'));
		} else {
			$data = $request->except('password');
		}
		
		$login_user = Auth::user();
		if($login_user->inRole('admin')){
			$parent_client = 0;
			if($request->input('user_type') == 'client'){
				$data['parent_user'] = $login_user->id;
			} else {
				$data['parent_user'] = $request->input('client_id');
				$data['parent_client'] = $login_user->id;
			}
		}
        $user->update($data);
		
		$request->session()->flash('success','User updated successfully');
		
		return response()->json(['success' => true, 'redirect' => route('user.index')]);
    }
}

resources/views/pages/user/form.blade.php
@extends('layouts.default')
@section('title', $data['page_title'])

@section('content')
<div class="content-wrapper">
	<section class="content-header">
      <h1>{{ $data['page_title'] }}
		<small>{{ $data['page_description'] }}</small>
	  </h1>
    </section>
	<section class="content">
		<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">{{ $data['page_description'] }}</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
			@if (count($errors) > 0)
				<div class="alert alert-danger">
					<strong>Whoops!</strong> There were some problems with your input.<br><br>
					<ul>
						@foreach ($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			
			@if($data['action'] == 'insert')
				{!! Form::open(array('route' => 'user.store', 'method'=>'POST', 'files' => true, 'id' => 'form-user')) !!}
			@else
				{!! Form::model($user, ['method' => 'PATCH','route' => ['user.update', $user->id], 'files' => true, 'id' => 'form-user']) !!}
			@endif
<div class="box-body">
	<div class="form-group required">
		{!! Form::label('name', 'Name') !!}
		{!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control', 'required' => 'required')) !!}
	</div>
	@can('see-only-admin')
		{{ Form::hidden('user_type', 'user') }}
		<div class="form-group" id="clients">
			{!! Form::label('client_id', 'Client') !!}
			{!! Form::select('client_id', $data['clients'], null, ['class' => 'form-control', 'placeholder' => 'Select Client', 'id' => 'client_id'])  !!}
		</div>
	@endcan
	<div class="form-group required">
		{!! Form::label('username', 'Username') !!}
		{!! Form::text('username', null, array('placeholder' => 'Name','class' => 'form-control', 'required' => 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('email', 'Email') !!}
		{!! Form::email('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
	</div>
	
	<div class="form-group">
		{!! Form::label('password', 'Password') !!}
		@if($data['action'] == 'insert')
			{!! Form::password('password', array('placeholder' => 'Password', 'class' => 'form-control', 'id' => 'password', 'required' => 'required')) !!}
		@else
			{!! Form::password('password', array('placeholder' => 'Password', 'class' => 'form-control', 'id' => 'password')) !!}
		@endif
	</div>
	
	<div class="form-group">
		{!! Form::label('status', 'Status') !!}
		{!! Form::select('status', ['active' => 'Active', 'inactive' => 'Inactive'] , null, ['class' => 'form-control'])  !!}
	</div>
</div>
<!-- /.box-body -->
<div class="box-footer">
	<button type="submit" class="btn btn-primary" id="button-submit">Submit</button>
	<a href="{{ route('user.index') }}" class="btn btn-danger pull-right">Back</a>
</div>

			{!! Form::close() !!}
          </div>
          <!-- /.box -->
          <!-- /.box -->
        </div>
      </div>
    </section>
</div>
@endsection

@section('scripts')
<meta name="csrf-token" content="{{ csrf_token() }}">
<script type="text/javascript">
$(function() {
	$.ajaxSetup({
		headers: {
			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
		}
	});
	$('#form-user').submit(function(e) {
		e.preventDefault();
		btn = $('#button-submit');
		$.ajax({
			url: '{{ $data["url"] }}',
			type: 'POST',
			data: $(this).serialize(),
			dataType: 'json',
			beforeSend: function() {
				btn.button('loading');
			},
			success: function(json) {
				$('.error-form-input').remove();
				btn.button('reset');
				if(json.errors){
					for (var input in json.errors) {
						var element = $('#' + input);
						$(element).after('<div class="text-danger error-form-input"><b>' + json['errors'][input] + '</b></div>');
					}
				} else if(json.success){
					location = json['redirect'];
				}
			}
		});
	});
});
</script>
@endsection

resources/views/pages/user/index.blade.php
@extends('layouts.default')
@section('title', 'User')

@section('styles')
<link rel="stylesheet" href="{{ asset('/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="content-wrapper">
    <section class="content-header">
      <h1>
        User
        <small>Information about user</small>
      </h1>
    </section>
    <section class="content">
		<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
				<a href="{{ route('user.create') }}" class="btn btn-danger btn-sm"><i class="fa fa-plus"></i> Add User</a>
              <div class="box-tools hidden">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
				@if (count($errors) > 0)
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<ul>
							@foreach ($errors->all() as $error)
								<li>{!! $error !!}</li>
							@endforeach
						</ul>
					</div>
				@endif
				@if ($message = Session::get('success'))
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<p>{{ $message }}</p>
					</div>
				@endif
              <table class="table table-bordered table-striped dataTable datatable">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						@can('see-only-admin')
						<th>Client</th>
						@endcan
						<th>Username</th>
						<th>Email</th>
						<th>Status</th>
						<th>Created Date</th>
						<th>Action</th>
					</tr>
				</thead>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
    </section>
</div>
@endsection

@section('scripts')
<script src="{{ asset('/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script type="text/javascript">
$(function() {
	 var oTable = $('.datatable').DataTable({
        processing: true,
        serverSide: true,
		pageLength: {{ Config::get('constants.wcst.page_limit') }},
        ajax: "{{ route('user.data') }}",
		order: [[0, 'desc']],
        columns: [
            {data: 'DT_Row_Index', name: 'id'},
            {data: 'name'},
			@can('see-only-admin'){data: 'parent_client.name', name: 'parent_client.name', defaultContent: "-", orderable: false, searchable: false},@endcan
            {data: 'username', orderable: false},
			{data: 'email', orderable: false},
            {data: 'status', orderable: false, searchable: false},
            {data: 'created_at', orderable: false},
			{data: 'action', orderable: false, searchable: false},
        ],
    });
});
</script>
@endsection