routes/web.php
<?php
/* Route::get('/', function () {
    return view('welcome');
}); */

//Auth::routes();

Route::get('{slug}', function() {
    return view('home');
})->where('slug', '(?!api|admin)([A-z\d-\/_.]+)?');

Route::group(['prefix' => 'admin'], function () {
	Route::get('/', 'Auth\LoginController@showLoginForm');
	Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'Auth\LoginController@login')->name('login');
	Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('/dashboard', 'Pages\MainController@index')->name('dashboard');
	Route::get('/user/getdata', 'Pages\UserController@getData')->name('user.data');
	Route::resource('user','Pages\UserController');
	Route::get('/client/getdata', 'Pages\ClientController@getData')->name('client.data');
	Route::get('/client/{client_id}/users', 'Pages\ClientController@getUsers');
	Route::resource('client','Pages\ClientController');
	Route::get('/staff/getdata', 'Pages\StaffController@getData')->name('staff.data');
	Route::resource('staff','Pages\StaffController');
	Route::get('/document/getdata', 'Pages\DocumentController@getData')->name('document.data');
	Route::resource('document','Pages\DocumentController');
	Route::get('/chat', 'Pages\ChatController@index')->name('chat.index');
	Route::post('/chat/{document}', 'Pages\ChatController@store')->name('chat.store');
	Route::get('/chat/{document}', 'Pages\ChatController@getData')->name('chat.data');
	Route::delete('/chat/{document}', 'Pages\ChatController@destroy')->name('chat.destroy');
	Route::get('/message/getdata', 'Pages\ChatController@getMessageData')->name('message.data');
	Route::get("/chat/count/data",'Pages\ChatController@chatCount')->name('chat.count');
	Route::post('/document/{document}/status', 'Pages\DocumentController@changeStatus')->name('document.status');
});

app/Http/Controllers/Pages/StaffController.php
<?php 
namespace App\Http\Controllers\Pages;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\User;
use Config;
use DataTables;
use Validator;
use Carbon\Carbon;
use Gate;

class StaffController extends Controller {
	
	public function __construct() {
        $this->middleware('auth');
		$this->middleware('admin');
    }
	
    public function index()
	{
        return view('pages.staff.index');
    }
	
	public function getData()
	{
		$user = Auth::user();
		if($user->inRole('super')){
			$query = User::whereHas('roles', function($q){
				$q->where('slug', 'admin');
			});
		} else if($user->inRole('admin')) {
			$user_id = $user->id;
			$query = User::whereHas('roles', function($q){
				$q->where('slug', 'staff');
			})->where('parent_user', $user_id);
		}

		return DataTables::eloquent($query)
		->addIndexColumn()
		->addColumn('action', function($user){
			$buttons = '<a href="'.route('staff.edit', $user->id).'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
			return $buttons;
		})
		->editColumn('parent_client.name', function($user){
			if($user->parent_client){
				return $user->parentClient->name;
			}
			return "-";
		})
		->editColumn('created_at', function($user){
			return $user->created_at ? with(new Carbon($user->created_at))->format('d/m/Y') : '';
		})
		->filterColumn('created_at', function ($query, $keyword) {
             $query->whereRaw("DATE_FORMAT(created_at,'%d/%m/%Y') like ?", ["%$keyword%"]);
        })
        ->rawColumns(['checkbox', 'action'])
		->toJson();
    }
	
	public function create()
    {
		$data['page_title'] = 'Add Staff';
		$data['page_description'] = 'Information about staff';
		$data['action'] = 'insert';
		$data['url'] = route('staff.store');
		
		$user = Auth::user();
		if($user->inRole('admin')) {
			$data['clients'] = User::whereHas('roles', function($q){
				$q->where('slug', 'client');
			})->where('parent_user',$user->id)->pluck('name', 'id');
			
			$data['document_type'] = [
				'All' => 'All Documents',
				'Purchase Bill'	=> 'Purchase Bill',
				'Sales Bill'	=> 'Sales Bill',
				'Expense Bill'	=> 'Expense Bill',
				'Payment'		=> 'Payment',
				'Others'		=> 'Others',
			];
		}
		
        return view('pages.staff.form', compact('data'));
    }
	
	public function store(Request $request)
    {
		$validator = Validator::make($request->all(), [
            'name' => 'required',
            'username' => 'required|unique:users|max:20',
            'email' => 'nullable|email|unique:users',
            'password' => 'required|min:6',
			'client.*.client_id' => 'required',
			'client.*.document_type.*' => 'required',
        ]);
		
		if ($validator->fails()) {
            return response()->json(['errors' => $validator->messages()]);
        }
		
		$login_user = Auth::user();
		$parent_user = $login_user->id;
		
		$user = User::create([
			'name' => $request->input('name'),
			'username' => $request->input('username'),
			'email' => $request->input('email'),
			'password' => bcrypt($request->input('password')),
			'status' => $request->input('status'),
			'parent_user' => $parent_user,
			'parent_client' => 0,
		]);
		
		$clients = $request->input('client');
		if(!empty($clients)){
			foreach($clients as $client){
				if(in_array('All', $client['document_type'])){
					$document_type = implode(',', array('Purchase Bill', 'Sales Bill', 'Expense Bill', 'Payment', 'Others'));
				} else {
					$document_type = implode(',', $client['document_type']);
				}
				$user->staffAccess()->create([
					'client_id' => $client['client_id'],
					'document_type' => $document_type
				]);
			}
		}
		
		$user->roles()->attach(5);
		
		$request->session()->flash('success','Staff user created successfully');
		return response()->json(['success' => true, 'redirect' => route('staff.index')]);
	}
	
	public function edit(User $staff)
	{
		$user = $staff;
		if (Gate::denies('user-access', $user)) {
			abort(404);
		}
		
		$data['page_title'] = 'Edit User';
		$data['page_description'] = 'Information about user';
		$data['action'] = 'edit';
		
		$login_user = Auth::user();
		if($login_user->inRole('admin')) {
			$data['clients'] = User::whereHas('roles', function($q){
				$q->where('slug', 'client');
			})->where('parent_user', $login_user->id)->pluck('name', 'id');
			
			$data['document_type'] = [
				'All' => 'All Documents',
				'Purchase Bill'	=> 'Purchase Bill',
				'Sales Bill'	=> 'Sales Bill',
				'Expense Bill'	=> 'Expense Bill',
				'Payment'		=> 'Payment',
				'Others'		=> 'Others',
			];
		}
		
		$data['url'] = route('staff.update', $user->id);
		
        return view('pages.staff.form', compact('user', 'data'));
    }
	
	public function update(Request $request, User $staff) 
	{
		$user = $staff;
		$validator = Validator::make($request->all(), [
            'name' => 'required',
            'username' => 'required|max:20|unique:users,username,'.$user->id,
            'email' => 'nullable|unique:users,email,'.$user->id,
            'password' => 'min:6|nullable',
			'client.*.client_id' => 'required',
			'client.*.document_type.*' => 'required',
        ]);
		
		if ($validator->fails()) {
            return response()->json(['errors' => $validator->messages()]);
        }
		
		if ($request->filled('password')) {
			$data = $request->except('client');
			$data['password'] = bcrypt($request->input('password'));
		} else {
			$data = $request->except('password', 'client');
		}
		
        $user->update($data);
		
		$clients = $request->input('client');
		if(!empty($clients)){
			$user->staffAccess()->delete();
			foreach($clients as $client){
				if(in_array('All', $client['document_type'])){
					$document_type = implode(',', array('Purchase Bill', 'Sales Bill', 'Expense Bill', 'Payment', 'Others'));
				} else {
					$document_type = implode(',', $client['document_type']);
				}
				$user->staffAccess()->create([
					'client_id' => $client['client_id'],
					'document_type' => $document_type
				]);
			}
		}
		
		$request->session()->flash('success','User updated successfully');
		
		return response()->json(['success' => true, 'redirect' => route('staff.index')]);
    }
}

resources/views/pages/staff/form.blade.php
@extends('layouts.default')
@section('title', $data['page_title'])

@section('content')
<div class="content-wrapper">
	<section class="content-header">
      <h1>{{ $data['page_title'] }}
		<small>{{ $data['page_description'] }}</small>
	  </h1>
    </section>
	<section class="content">
		<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">{{ $data['page_description'] }}</h3>
            </div>
			@if (count($errors) > 0)
				<div class="alert alert-danger">
					<strong>Whoops!</strong> There were some problems with your input.<br><br>
					<ul>
						@foreach ($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			
			@if($data['action'] == 'insert')
				{!! Form::open(array('route' => 'staff.store', 'method'=>'POST', 'files' => true, 'id' => 'form-user')) !!}
			@else
				{!! Form::model($user, ['method' => 'PATCH','route' => ['staff.update', $user->id], 'files' => true, 'id' => 'form-user']) !!}
			@endif
<div class="box-body">
	<div class="form-group required">
		{!! Form::label('name', 'Name') !!}
		{!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control', 'required' => 'required')) !!}
	</div>
	<div class="form-group required">
		{!! Form::label('username', 'Username') !!}
		{!! Form::text('username', null, array('placeholder' => 'Name','class' => 'form-control', 'required' => 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('email', 'Email') !!}
		{!! Form::email('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('password', 'Password') !!}
		@if($data['action'] == 'insert')
			{!! Form::password('password', array('placeholder' => 'Password', 'class' => 'form-control', 'id' => 'password', 'required' => 'required')) !!}
		@else
			{!! Form::password('password', array('placeholder' => 'Password', 'class' => 'form-control', 'id' => 'password')) !!}
		@endif
	</div>
	<div class="row-fluid clearfix">
		<div class="col-sm-12 well well-sm catering-menu-area">
			<p class="lead">Client</p>
			
			@if($user->staffAccess->isNotEmpty())
				@foreach ($user->staffAccess as $i => $staff_access)
					<div class="catering_menu col-sm-12 form-group" data-count="{{ $i }}">
					<div class="col-sm-3 form-group">
						{!! Form::select('client['.$i.'][client_id]', $data['clients'], $staff_access->client_id, array('class' => 'form-control', 'required' => 'required', 'placeholder' => 'Select Client')) !!}
					</div>
					<div class="col-sm-3 form-group">
						@if(explode(',', $staff_access->document_type) === array('Purchase Bill', 'Sales Bill', 'Expense Bill', 'Payment', 'Others'))
							{!! Form::select('client['.$i.'][document_type][]', $data['document_type'], 'All', array('class' => 'form-control', 'required' => 'required', 'multiple' => true)) !!}
						@else
							{!! Form::select('client['.$i.'][document_type][]', $data['document_type'], explode(',', $staff_access->document_type), array('class' => 'form-control', 'required' => 'required', 'multiple' => true)) !!}
						@endif
					</div>
					<div class="col-sm-3 form-group">
						@if ($i == 0)
							<button type="button" class="btn btn-success btn-sm btn_add_menu"><i class="fa fa-plus"></i> Add Client</button>
						@else
							<button type="button" class="btn btn-danger btn-sm btn_remove_catering"><i class="fa fa-minus"></i> Remove</button>
						@endif
					</div>
				</div>
				@endforeach
			@else
			<div class="catering_menu col-sm-12 form-group" data-count="0">
				<div class="col-sm-3 form-group">
					{!! Form::select('client[0][client_id]', $data['clients'], null, array('class' => 'form-control', 'required' => 'required', 'placeholder' => 'Select Client')) !!}
				</div>
				<div class="col-sm-3 form-group">
					{!! Form::select('client[0][document_type][]', $data['document_type'], null, array('class' => 'form-control', 'required' => 'required', 'multiple' => true)) !!}
				</div>
				<div class="col-sm-3 form-group">
					<button type="button" class="btn btn-success btn-sm btn_add_menu"><i class="fa fa-plus"></i> Add Client</button>
				</div>
			</div>
			@endif
		</div>
	</div>
	<div class="form-group">
		{!! Form::label('status', 'Status') !!}
		{!! Form::select('status', ['active' => 'Active', 'inactive' => 'Inactive'] , null, ['class' => 'form-control'])  !!}
	</div>
</div>
<div class="box-footer">
	<button type="submit" class="btn btn-primary" id="button-submit">Submit</button>
	<a href="{{ route('staff.index') }}" class="btn btn-danger pull-right">Back</a>
</div>

			{!! Form::close() !!}
          </div>
        </div>
      </div>
    </section>
</div>
@endsection

@section('scripts')
<meta name="csrf-token" content="{{ csrf_token() }}">
<script type="text/javascript">
$(function() {
	var main_count = 1;
	$(document).delegate('.btn_add_menu', 'click', function() {
		
		if($('.catering_menu').length > 1){
			main_count = $('.catering-menu-area').children('.catering_menu').last().data('count') + 1;
		}
		
		var html = '<div class="catering_menu col-sm-12 form-group" data-count="'+main_count+'">';
		
		html += '<div class="col-sm-3 form-group">';
		html += '<select class="form-control" required="required" name="client['+main_count+'][client_id]">';
		html += $('select[name="client[0][client_id]"]').html();
		html += '</select>';
		html += '</div>';
		
		html += '<div class="col-sm-3 form-group">';
		html += '<select class="form-control" required="required" name="client['+main_count+'][document_type][]" multiple>';
		html += $('select[name="client[0][document_type][]"]').html();
		html += '</select>';
		html += '</div>';
		
		html += '<div class="col-sm-3 form-group">';
		html += '<button type="button" class="btn btn-danger btn-sm btn_remove_catering"><i class="fa fa-minus"></i> Remove</button>';
		html += '</div>';
		
		html += '</div>';
		
		$('.catering-menu-area').append(html);
		main_count++;
	});
	
	$(document).delegate('.btn_remove_catering', 'click', function() {
		$(this).closest('.catering_menu').remove();
	});
	
	$.ajaxSetup({
		headers: {
			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
		}
	});
	$('#form-user').submit(function(e) {
		e.preventDefault();
		btn = $('#button-submit');
		$.ajax({
			url: '{{ $data["url"] }}',
			type: 'POST',
			data: $(this).serialize(),
			dataType: 'json',
			beforeSend: function() {
				btn.button('loading');
			},
			success: function(json) {
				$('.error-form-input').remove();
				btn.button('reset');
				if(json.errors){
					for (var input in json.errors) {
						var element = $('#' + input);
						$(element).after('<div class="text-danger error-form-input"><b>' + json['errors'][input] + '</b></div>');
					}
				} else if(json.success){
					location = json['redirect'];
				}
			}
		});
	});
});
</script>
@endsection

resources/views/pages/staff/index.blade.php
@extends('layouts.default')
@section('title', 'Staff')

@section('styles')
<link rel="stylesheet" href="{{ asset('/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="content-wrapper">
    <section class="content-header">
      <h1>
        Staff
        <small>Information about staff</small>
      </h1>
    </section>
    <section class="content">
		<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
				<a href="{{ route('staff.create') }}" class="btn btn-danger btn-sm"><i class="fa fa-plus"></i> Add Staff</a>
              <div class="box-tools hidden">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
				@if (count($errors) > 0)
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<ul>
							@foreach ($errors->all() as $error)
								<li>{!! $error !!}</li>
							@endforeach
						</ul>
					</div>
				@endif
				@if ($message = Session::get('success'))
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<p>{{ $message }}</p>
					</div>
				@endif
              <table class="table table-bordered table-striped dataTable datatable">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Username</th>
						<th>Email</th>
						<th>Status</th>
						<th>Created Date</th>
						<th>Action</th>
					</tr>
				</thead>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
    </section>
</div>
@endsection

@section('scripts')
<script src="{{ asset('/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script type="text/javascript">
$(function() {
	 var oTable = $('.datatable').DataTable({
        processing: true,
        serverSide: true,
		pageLength: {{ Config::get('constants.wcst.page_limit') }},
        ajax: "{{ route('staff.data') }}",
		order: [[0, 'desc']],
        columns: [
            {data: 'DT_Row_Index', name: 'id'},
            {data: 'name'},
			{data: 'username', orderable: false},
            {data: 'email', orderable: false},
            {data: 'status', orderable: false, searchable: false},
            {data: 'created_at', orderable: false},
			{data: 'action', orderable: false, searchable: false},
        ],
    });
});
</script>
@endsection