routes/web.php
<?php
/* Route::get('/', function () {
    return view('welcome');
}); */

//Auth::routes();

Route::get('{slug}', function() {
    return view('home');
})->where('slug', '(?!api|admin)([A-z\d-\/_.]+)?');

Route::group(['prefix' => 'admin'], function () {
	Route::get('/', 'Auth\LoginController@showLoginForm');
	Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'Auth\LoginController@login')->name('login');
	Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('/dashboard', 'Pages\MainController@index')->name('dashboard');
	Route::get('/user/getdata', 'Pages\UserController@getData')->name('user.data');
	Route::resource('user','Pages\UserController');
	Route::get('/client/getdata', 'Pages\ClientController@getData')->name('client.data');
	Route::get('/client/{client_id}/users', 'Pages\ClientController@getUsers');
	Route::resource('client','Pages\ClientController');
	Route::get('/staff/getdata', 'Pages\StaffController@getData')->name('staff.data');
	Route::resource('staff','Pages\StaffController');
	Route::get('/document/getdata', 'Pages\DocumentController@getData')->name('document.data');
	Route::resource('document','Pages\DocumentController');
	Route::get('/chat', 'Pages\ChatController@index')->name('chat.index');
	Route::post('/chat/{document}', 'Pages\ChatController@store')->name('chat.store');
	Route::get('/chat/{document}', 'Pages\ChatController@getData')->name('chat.data');
	Route::delete('/chat/{document}', 'Pages\ChatController@destroy')->name('chat.destroy');
	Route::get('/message/getdata', 'Pages\ChatController@getMessageData')->name('message.data');
	Route::get("/chat/count/data",'Pages\ChatController@chatCount')->name('chat.count');
	Route::post('/document/{document}/status', 'Pages\DocumentController@changeStatus')->name('document.status');
});

app/Chat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Chat extends Model
{
    protected $fillable = [
        'document_id', 'user_id', 'message', 'status'
    ];

    protected $hidden = [
        'document_id', 'updated_at'
    ];
	
	public function getCreatedAtAttribute($date)
	{
		return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d-m-Y h:i A');
	}
	public function user() 
	{
        return $this->belongsTo('App\User');
    }
	public function document() 
	{
        return $this->belongsTo('App\Document');
    }
}

resources/views/includes/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; {!! date('Y') !!} <a href="#">Document Collection</a>.</strong> All rights reserved.
</footer>

resources/views/includes/header.blade.php
<header class="main-header">
    <a href="{{ route('dashboard') }}" class="logo">
      <span class="logo-mini"><b>L</b></span>
      <span class="logo-lg"><b>LOGO</b></span>
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ url('/dist/img/avatar5.png') }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ Auth::user()->name }}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <img src="{{ url('/dist/img/avatar5.png') }}" class="img-circle" alt="User Image">
                <p>
                  {{ Auth::user()->name }}
                  <small>Member since {{ \Carbon\Carbon::parse(Auth::user()->created_at)->format('M.Y')}}</small>
                </p>
              </li>
              <li class="user-footer">
			  <div class="pull-left">
                  <a href="{{-- route('profile.index') --}}" class="btn btn-default btn-flat">Profile</a>
              </div>
                <div class="pull-right">
                  <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Sign out</a>
				  
				  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
					{{ csrf_field() }}
                  </form>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/includes/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ url('/dist/img/avatar5.png') }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
        </div>
      </div>
      <ul class="sidebar-menu" data-widget="tree">
        <li class="{{ Request::is('admin/dashboard') ? 'active' : '' }}"><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
		@can('see-only-admin')
		<li class="{{ Request::is('admin/client') ? 'active' : '' }}">
          <a href="{{ route('client.index') }}"><i class="fa fa-cc"></i> 
			<span>Client</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
			</span>
          </a>
        </li>
		
		<li class="{{ Request::is('admin/staff') ? 'active' : '' }}">
          <a href="{{ route('staff.index') }}"><i class="fa fa-skype"></i> 
			<span>Staff</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
			</span>
          </a>
        </li>
		@endcan
		@if(Gate::check('see-only-super') || Gate::check('see-only-admin'))
		<li class="{{ Request::is('admin/user') ? 'active' : '' }}">
          <a href="{{ route('user.index') }}"><i class="fa fa-user"></i> 
		  @can('see-only-super')
			<span>CA</span>
		  @endcan
		  @can('see-only-admin')
			<span>User</span>
		  @endcan
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
        </li>
		@endif
		
		@if(Gate::check('see-only-admin') || Gate::check('see-only-client') || Gate::check('see-only-staff'))
		<li class="{{ Request::is('admin/document') ? 'active' : '' }}">
          <a href="{{ route('document.index') }}"><i class="fa fa-file"></i>
			<span>Documents</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red unread_doc">0</small>
            </span>
          </a>
        </li>
		<li class="{{ Request::is('admin/chat') ? 'active' : '' }}">
          <a href="{{ route('chat.index') }}"><i class="fa fa-envelope"></i>
			<span>Message</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red unread_chat">0</small>
            </span>
          </a>
        </li>
		@endif
      </ul>
    </section>
</aside>